site_name: Awesome Tutos
repo_url: https://github.com/louisguitton/awesome-tutos
site_description: A curated list of tech tutos to share and to refer back to.
site_author: Louis Guitton

nav:
    - Home: index.md
    - Guides:
        - Tech Guides:
            - Docs: guides/tech/readme.md
            - Python: guides/tech/python.md
            - Git: guides/tech/git.md
            - SQL: guides/tech/sql.md
            - dbt: guides/tech/dbt.md
            - Backend: guides/tech/backend.md
            - docker: guides/tech/docker.md
            - CI: guides/tech/ci.md
        - Infrastructure:
            - Data Stack: guides/infra/data-stack.md
            - AWS: guides/tech/aws.md
        - Data Team:
            - Roles: guides/team/data-team-roles.md
            - Code Review: guides/team/code-review.md
            - Applied ML Research: guidse/team/applied-ml-research.md
            - Project Management: guides/team/project-management.md
